### ISSUE TITLE
napalm not installing due to broken procees

### ISSUE THREAD

**Issue by Abbasjafri-syed** [ConsenSysDiligence/napalm#5]
@JoranHonig  whenever i run ```pip3 install napalm-toolbox``` it ran succesfully but facing this issue when running ```$ pip3 install napalm-base```

```
 ModuleNotFoundError: No module named 'pip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JoranHonig** [comment]
Is this all the output you're getting or is there more?

What os and python version are you using?

**Comment by shortdoom** [comment]
I subbed to this Issue earlier as I thought about contributing to napalm, but also ran into the same error.

The issue is that there's no napalm-base package on pypi available. Did you guys make it public? napalm-base-1.0.0 is an old package that uses python 3.4.

```
(venv) user@nest:~/Github/Bugz/napalm$ pip install napalm-base
Collecting napalm-base
  Using cached napalm-base-1.0.0.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'pip'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JoranHonig** [comment]
Apologies I'd forgotten to update the docs.

Can you try `pip install napalm-core`?

**Comment by Abbasjafri-syed** [comment]
> I subbed to this Issue earlier as I thought about contributing to napalm, but also ran into the same error.
> 
> The issue is that there's no napalm-base package on pypi available. Did you guys make it public? napalm-base-1.0.0 is an old package that uses python 3.4.
> 
> ```
> (venv) user@nest:~/Github/Bugz/napalm$ pip install napalm-base
> Collecting napalm-base
>   Using cached napalm-base-1.0.0.tar.gz (35 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Traceback (most recent call last):
>         File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/user/Github/Bugz/napalm/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-36tztpq3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
>           exec(code, locals())
>         File "<string>", line 5, in <module>
>       ModuleNotFoundError: No module named 'pip'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

@JoranHonig this error in full

**Comment by shortdoom** [comment]
I think there's still some naming confusion in cli

```
(venv) user@nest:~/Github/Bugz/napalm$ python --version
Python 3.12.2
(venv) user@nest:~/Github/Bugz/napalm$ napalm collections show
Usage: napalm collections show [OPTIONS] COLLECTION
Try 'napalm collections show --help' for help.
Error: Missing argument 'COLLECTION'.
(venv) user@nest:~/Github/Bugz/napalm$ napalm collections list
Installed collections:
  - napalm-base/optimisations
  - napalm-base/detectors
  - napalm-base/indicators
(venv) user@nest:~/Github/Bugz/napalm$ napalm collections show napalm-core/detectors
Collection napalm-core/detectors not found!
(venv) user@nest:~/Github/Bugz/napalm$ napalm collections show napalm-base/detectors
int-cast-block-timestamp - [WARNING] Casting block.timestamp can lead to reduced precision and unexpected behavior, consider not casting instead.
use-of-unsafe-erc20-functions - [INFO] The ERC20 implementation does not automatically include checks that ensure the success of the operation. Using the OpenZeppelin's SafeERC20 library is 
recommended.
block-timestamp-swap - [WARNING] Passing block.timestamp as the deadline effectively removes the deadline functionality which prevents malicious validators from holding back transactions to 
execute them at a later time.

napalm-base/detectors summary:
  - 3 semgrep rules
```

Notice that I needed to use `napalm-base/detectors`. I also successfully did it only on locally installed package (after git pulling _base<>core_ change), as in 

```
(venv) user@nest:~/Github/Bugz/napalm$ pip freeze 
napalm-core==0.1.1
-e git+https://github.com/ConsenSysDiligence/napalm.git@6304e6dfd5d8407fa67cb8a7052eb80d6614b9f5#egg=napalm_toolbox
```

`napalm-toolbox` from pypi seems to throw other cli error.

```
(venv) user@nest:~/Github/Bugz/temp$ napalm collections show
Traceback (most recent call last):
  File "/home/user/Github/Bugz/temp/venv/bin/napalm", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/napalm/cli/base/main.py", line 25, in cli
    auto_install_hook(ctx.obj["storage"])
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/napalm/cli/base/auto.py", line 27, in auto_install_hook
    _removed_collections(storage_provider)
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/napalm/cli/base/auto.py", line 31, in _removed_collections
    removed_collections = list(_get_removed_collections(storage_provider))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/napalm/cli/base/auto.py", line 155, in _get_removed_collections
    used_collections = pipe(
                       ^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 628, in pipe
    data = func(data)
           ^^^^^^^^^^
  File "/home/user/Github/Bugz/temp/venv/lib/python3.12/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: reduce() of empty iterable with no initial value
```

**Comment by JoranHonig** [comment]
Fixed the naming issue in napalm-core!

The reduce bug should also be resolved in the latest napalm version.

---

Thanks for bearing with me!

**Comment by shortdoom** [comment]
Yep, all of the previously mentioned are now working! I opened the PR with some of other things that were stopping successfully running workflows. I also opened another issue in relation to slither modules that are still failing but it's outside of the scope of this issue.

**Comment by JoranHonig** [comment]
Awesome!

I'll close this issue 🚀
